repos:
  # pre-commit install --hook-type pre-push
  - repo: https://github.com/pre-commit/pre-commit-hooks # Generic review/format
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier/ # Generic review/format
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli # Format markdown
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: ["--fix", "--disable", "MD036"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
        # For running trufflehog in docker, use the following entry instead:
        # entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["commit", "push"]
